
-- CREACIÓN DE LA BASE DE DATOS
CREATE DATABASE registro;
USE registro;

-- TABLA DE USUARIOS (Para el Login de la Directora)
CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_usuario VARCHAR(100) NOT NULL,
    usuario VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
);

-- TABLA DE DOCENTES (10 Registros)
CREATE TABLE docentes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dni VARCHAR(8) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    especialidad VARCHAR(50) NOT NULL
);

-- TABLA DE ASISTENCIA (Relacionada con docentes)
CREATE TABLE asistencia (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dni_docente VARCHAR(8) NOT NULL,
    fecha DATE NOT NULL,
    hora_entrada TIME NOT NULL,
    estado VARCHAR(20) NOT NULL
);

-- DATOS INICIALES
INSERT INTO usuarios (nombre_usuario, usuario, password) 
VALUES ('JOSE OLAYA BALANDRA', 'admin', '1234');

INSERT INTO docentes (dni, nombre, especialidad) VALUES 
('10000001', 'MIGUEL PONCE', 'MATEMATICA'),
('10000002', 'ROSA MARIEL', 'COMUNICACION'),
('10000003', 'RAUL TORRES', 'CIENCIA Y TECNOLOGIA'),
('10000004', 'ANA LUZ VALDÉS', 'INGLES'),
('10000005', 'CARLOS MENDOZA', 'EDUCACION FISICA'),
('10000006', 'ELENA GUERRA', 'ARTE Y CULTURA'),
('10000007', 'JORGE LINARES', 'HISTORIA'),
('10000008', 'SONIA QUISPE', 'RELIGION'),
('10000009', 'PEDRO ALVARADO', 'COMPUTO'),
('10000010', 'CARMEN REYES', 'CIENCIAS SOCIALES');
